#!/usr/bin/env bash

############################################## <Color> ##############################################
RED='\033[0;31m'
NC='\033[0m' # No Color
############################################## </Color> ##############################################

mkdir -p dev

logs_path=.ci/controllers-test/logs
TEST_RESULT=
cli_path=/cc/utils/cli.py
num_of_existing_nodes=1
TEST_SHOOT=aws-ci-it
CREDENTIALS_SECRET_NAME=shoot-operator-aws-team

#these variables are accessed in test/integration/controller so prefixed by ${SOURCE_PATH} for absolute path
declare CONTROL_KUBECONFIG=${SOURCE_PATH}/dev/control_kubeconfig.yaml
declare TARGET_KUBECONFIG=${SOURCE_PATH}/dev/target_kubeconfig.yaml

export CONTROL_KUBECONFIG
export TARGET_KUBECONFIG
export MACHINECLASS_V1=${SOURCE_PATH}/dev/v1machineclass_converted.yaml
export MACHINE_CONTROLLER_MANAGER_DEPLOYMENT_NAME="machine-controller-manager"

############################################## <Helper fn> ##############################################

function hf_num_of_objects() {
    output=$(kubectl --kubeconfig=dev/control_kubeconfig.yaml get "$1" | grep machine.sapcloud.io 2>&1)
    
    if [ -z "$output" ]; then
       return 0 
    fi

    object_count=$(echo "$output" | wc -l)

    return "$object_count"
}

function hf_num_of_ready_nodes() {
    output=$(kubectl --kubeconfig=dev/target_kubeconfig.yaml get "$1" 2>&1)
    
    ready_count=$(echo "$output" | tr " " "\n" | grep ^Ready -c)

    return $((ready_count-num_of_existing_nodes))
}

function hf_wait_on() {
    function_name=$1
    function_param=$2
    count_to_match=$3
    seconds_to_wait=$4
    iteration_count=$(($seconds_to_wait/30))

    while
        "$function_name" "$function_param"
        ret=$?
        [[ $ret -ne $count_to_match ]]
    do
        sleep 30
        ((iteration_count--))

        # Exit script when timeout occurs
        if [ $iteration_count -le 0 ]; then
            printf "\tFailed: Timeout occured while waiting for operation. Exiting Test to avoid further conflicts.\n"
            printf "\tWas Executing function: %s, %s\n" $function_name $function_param
            printf "${RED}There is another PR running its integration test on the clusters. Waiting Timed Out. Kindly re-run the tests.${NC}\n"
            exit 1
        fi

    done
}

############################################## </Helper fn> ##############################################


############################################## <Initialization> ##############################################

function setup_ginkgo() {
    echo "Installing Ginkgo..."
    GO111MODULE=off go get -u github.com/onsi/ginkgo/ginkgo
    ginkgo version
    echo "Successfully installed Ginkgo."
}

# Fetch service account kubeconfig
function fetch_service_account_kubeconfig() {
    ${cli_path} config attribute --cfg-type kubernetes --cfg-name mcm-ci-garden-dev-virtual --key kubeconfig  > dev/sa_kubeconfig.yaml
}

# Fetch *-oot-target and *-oot-control cluster kubeconfig
function fetch_oot_cluster_kubeconfig() {
    NAMESPACE=garden-mcm-ci
    SHOOT_NAME=aws-ci-it
    kubectl --kubeconfig=dev/sa_kubeconfig.yaml create -f <(printf '{"spec":{"expirationSeconds":3600}}') --raw /apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/adminkubeconfig | jq -r ".status.kubeconfig" | base64 -d > dev/target_kubeconfig.yaml
    kubectl --kubeconfig=dev/sa_kubeconfig.yaml create -f <(printf '{"spec":{"expirationSeconds":3600}}') --raw /apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/adminkubeconfig | jq -r ".status.kubeconfig" | base64 -d > dev/control_kubeconfig.yaml
}

function fetch_userdata_and_machineclass(){
    NAMESPACE='garden'
    kubectl --kubeconfig=dev/sa_kubeconfig.yaml get shoot $TEST_SHOOT -oyaml > dev/tmp3_secret.yaml
    SHOOT_NAME=$(yq eval '.status.seedName' dev/tmp3_secret.yaml)
    kubectl --kubeconfig=dev/sa_kubeconfig.yaml create -f <(printf '{"spec":{"expirationSeconds":3600}}') --raw /apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/adminkubeconfig | jq -r ".status.kubeconfig" | base64 -d > dev/seed_kubeconfig.yaml
    USERDATA_SECRET_NAME=$(kubectl --kubeconfig=dev/seed_kubeconfig.yaml get secrets -n shoot--mcm-ci--$TEST_SHOOT -o custom-columns=Name:.metadata.name --no-headers | grep shoot--mcm-ci)
    kubectl --kubeconfig=dev/seed_kubeconfig.yaml get secret $USERDATA_SECRET_NAME -n shoot--mcm-ci--$TEST_SHOOT -oyaml > dev/tmp2_secret.yaml
    userData=$(yq eval '.data.userData' dev/tmp2_secret.yaml)
    echo $userData
    MCC_NAME=$(kubectl --kubeconfig=dev/seed_kubeconfig.yaml get mcc -n shoot--mcm-ci--$TEST_SHOOT -o custom-columns=Name:.metadata.name --no-headers | grep shoot--mcm-ci)
    kubectl --kubeconfig=dev/seed_kubeconfig.yaml get mcc $MCC_NAME -n shoot--mcm-ci--$TEST_SHOOT -oyaml > ${SOURCE_PATH}/dev/v1machineclass_converted.yaml
    yq eval 'del(.metadata.creationTimestamp) | del(.metadata.finalizers) | del(.metadata.generation) | del(.metadata.resourceVersion) | del(.metadata.uid) | del(.credentialsSecretRef)'  dev/v1machineclass_converted.yaml -i
    yq eval '.metadata.name = "test-mc-v1" | .metadata.namespace = "default" | .secretRef.name = "test-mc-secret" | .secretRef.namespace = "default"' dev/v1machineclass_converted.yaml -i
}

function fetch_credentials(){
   kubectl --kubeconfig=dev/sa_kubeconfig.yaml get secret $CREDENTIALS_SECRET_NAME -n garden-core -o yaml > dev/tmp_secret.yaml
   accessKeyID=$(yq eval '.data.accessKeyID' dev/tmp_secret.yaml)
   secretAccessKey=$(yq eval '.data.secretAccessKey' dev/tmp_secret.yaml)
   echo $accessKeyID
   echo $secretAccessKey
}

function create_test_mc_secret() {
    result=$(fetch_credentials)
    accessKeyID=$(echo "$result" | head -n 1)
    secretAccessKey=$(echo "$result" | tail -n 1)
    userData=$(fetch_userdata_and_machineclass)
    rm -f dev/tmp_secret.yaml
    rm -f dev/tmp2_secret.yaml
secret_yaml=$(cat <<EOF
apiVersion: v1
data:
  accessKeyID: $accessKeyID
  secretAccessKey: $secretAccessKey
  userData: $userData
kind: Secret
metadata:
  name: test-mc-secret
  namespace: default
type: Opaque
EOF
)
    echo "############ TEST_MC_SECRET ##############"
    echo "$secret_yaml"
    # uncommenting it will renew the secrets in pipeline IT.
    echo "$secret_yaml" | kubectl --kubeconfig=$CONTROL_KUBECONFIG apply -f -
}

function setup_environment() {
    printf "\n\t\t\t----- Setup Test Environment --------\n"

    #installing yq 
    printf "\nDownloading and installing yq\n"
    curl -LO https://github.com/mikefarah/yq/releases/download/v4.13.3/yq_linux_amd64
    chmod +x ./yq_linux_amd64
    mv ./yq_linux_amd64 /usr/local/bin/yq
    printf "Successfully installed yq\n"

    # install kubectl
    printf "\nDownloading and installing kubectl\n"
    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl
    printf "Successfully installed kubectl\n"

    #install ginkgo
    if ! [ -x "$(command -v ginkgo)" ]; then
    setup_ginkgo
    fi

    #fetching kubeconfigs and machineClass from secret_server
    fetch_service_account_kubeconfig
    fetch_oot_cluster_kubeconfig
    echo "######## Cluster Kubeconfig ##########"
    cat dev/target_kubeconfig.yaml
#    fetch_machine_class
    create_test_mc_secret
    echo "######## MACHINE CLASS #########"
    cat dev/v1machineclass_converted.yaml
}

function check_cluster_state() {
    printf "\t\t\t----- Checking Test Environment -------\n"

    printf "\nChecking existance of machine crds\n"
    # Wait 60mins for any existing PRs to cleanup machine crds, as crd cleanup is last step.
    hf_wait_on "hf_num_of_objects" crd 0 3600
    printf "No machine crds in control test cluster\n"

    printf "\nChecking existance of node objects\n"
    # Wait 60mins for any existing PRs to cleanup nodes
    hf_wait_on "hf_num_of_ready_nodes" nodes 0 3600
    printf "No additional node objects in target test cluster\n"

    #wait in case some orphan resources are terminating
    sleep 30
    
    printf "\nCluster state looks clean\n"
    printf "\t\t\t----- Checking Test Environment DONE -------\n"
}

############################################## </Initialization> ##############################################

############################################## <Modules> ########################################################

function run_integration_tests() {
    echo "Starting integration tests..."
    set +e

    ginkgo -v -mod=vendor test/integration/controller
    TEST_RESULT=$?
    
    set -e

    if [ ${TEST_RESULT} -ne 0 ]; then
        printf "\n\t\t\t${RED}Integration tests failed. Kindly check you PR${NC}\n"
    else
        printf "Done with integration test\n"
    fi
}

function print_controller_logs {
    printf "\n\t\t\t----- Start of MCM Logs -----------\n"
    cat $logs_path/mcm_process.log
    printf "\n\t\t\t----- End of MCM Logs   ----------\n\n"

    printf "\n\t\t\t----- Start of MC Logs -----------\n"
    cat $logs_path/mc_process.log
    printf "\n\t\t\t----- End of MC Logs   ----------\n\n"
}

############################################## </Modules> ########################################################


############################################## <Main> ########################################################

printf "\n\t\t\t----- Start of Test Script -----------\n"
setup_environment
#if cluster state is not clean then don't run the tests
check_cluster_state
result=$?
if [ ${result} -ne 0 ]; then
exit $result
fi
run_integration_tests
print_controller_logs
printf "\n\t\t\t----- End of Test Script -----------\n"

exit $TEST_RESULT

############################################## </Main> ########################################################
