# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Sample machine object

apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  name: test-machine
  namespace: default
spec:
  class:
    kind: MachineClass
    name: test-mc
    namespace: default
# nodeTemplate: 
#   metadata:
#     annotations:  
#       machine.sapcloud.io/awsPlacement: '{ "affinity": "host", "availabilityZone": "eu-west-1a", "tenancy": "host"}' # Optional: it allows placing machine on a dedicated host in an availability zone,assuming dedicated host has auto-placement enabled; affinity can be host only if tenancy is host
