name: Create Upgrade-Pull-Requests
on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  upgrade-pullrequests:
    uses: gardener/cc-utils/.github/workflows/upgrade-dependencies.yaml@v1
    permissions:
      contents: read
      id-token: write
    with:
      prepare-action-path: ./.github/actions/setup-go
